backend:
  name: github
  repo: profboumediene-prog/atelier-pes
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "ressources"
    label: "Ressources Pédagogiques"
    folder: "donnees/ressources"
    create: true
    fields:
      - {label: "Titre de la fiche", name: "titre", widget: "string"}
      - {label: "Format", name: "format", widget: "select", options: ["Word", "PDF"]}
      - {label: "Objet d'étude", name: "objet_etude", widget: "select", options: ["Textes et documents d'histoire", "Le débat d'idées", "L'appel", "La nouvelle fantastique"]}
      - {label: "Séquence", name: "sequence", widget: "select", options: ["Produire un texte pour informer d'un fait d'histoire de manière objective", "Produire un texte pour présenter un fait d'histoire avec commentaires/témoignages", "Produire un texte pour convaincre ou persuader", "Produire un texte pour concéder et réfuter", "Produire un texte pour inciter le destinataire à agir", "Produire un récit fantastique"]}
      - {label: "Lien de téléchargement (Google Drive)", name: "lien", widget: "string"}